version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
    networks:
      - app-network

  client-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - app-network

  neo4j:
    image: neo4j
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
